// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGcpOJWqcSqQz0P1iGArsz6Y0qFf-X-2I',
    appId: '1:307529195986:web:627171e9f1e2723bb7e80b',
    messagingSenderId: '307529195986',
    projectId: 'softdevuas',
    authDomain: 'softdevuas.firebaseapp.com',
    storageBucket: 'softdevuas.appspot.com',
    measurementId: 'G-V9MRYEE8RY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBagYyds3GQ3wp2LbMzcVjKorGwxbJSaQs',
    appId: '1:307529195986:android:6310bec34a10e0d3b7e80b',
    messagingSenderId: '307529195986',
    projectId: 'softdevuas',
    storageBucket: 'softdevuas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe3Xh9wY5YVSxouOSYxeAqCOL27ylHxrw',
    appId: '1:307529195986:ios:3caf78425bd10047b7e80b',
    messagingSenderId: '307529195986',
    projectId: 'softdevuas',
    storageBucket: 'softdevuas.appspot.com',
    iosClientId:
        '307529195986-u3l1s4u4qjbublmdtckbe0krf1so7bet.apps.googleusercontent.com',
    iosBundleId: 'com.nata.softdevuas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe3Xh9wY5YVSxouOSYxeAqCOL27ylHxrw',
    appId: '1:307529195986:ios:3caf78425bd10047b7e80b',
    messagingSenderId: '307529195986',
    projectId: 'softdevuas',
    storageBucket: 'softdevuas.appspot.com',
    iosClientId:
        '307529195986-u3l1s4u4qjbublmdtckbe0krf1so7bet.apps.googleusercontent.com',
    iosBundleId: 'com.nata.softdevuas',
  );
}


// import 'package:firebase_core/firebase_core.dart';
// import 'firebase_options.dart';
// ...

// await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
// );